form-data/form-data

lib/form_data.js
package.json
test/integration/test-last_boundary-line_break.js

#109 Append proper line break

---

lib/form_data.js
test/integration/test-custom-filename.js

Allow filename as third option of #append

---

lib/form_data.js
test/integration/test-custom-filename.js
test/integration/test-pipe.js
test/integration/test-submit-custom-header.js
test/integration/test-submit-custom.js
test/integration/test-submit.js

Resolves https://github.com/felixge/node-form-data/issues/118.
Also fixes https://github.com/felixge/node-form-data/pull/54.

Default content-type to 'application/octect-stream'

---

Readme.md

Resolve https://github.com/felixge/node-form-data/issues/131.

Add node-fetch to alternative submission methods.

---

lib/form_data.js

This is in accordance with https://github.com/felixge/node-form-data/issues/124.

Should throw type error without new operator.

---

lib/form_data.js

Trying to setup code monitoring. :)
/cc @DylanPiercey

Cleaned up codacity concerns.

---

.editorconfig
.eslintrc
Makefile
lib/form_data.js
package.json
test/common.js
test/integration/test-custom-content-type.js
test/integration/test-custom-filename.js
test/integration/test-custom-headers.js
test/integration/test-errors.js
test/integration/test-form-get-length-sync.js
test/integration/test-form-get-length.js
test/integration/test-http-response.js
test/integration/test-last_boundary-line_break.js
test/integration/test-pipe.js
test/integration/test-ranged-filestream.js
test/integration/test-request.js
test/integration/test-return-http-request.js
test/integration/test-submit-custom-header.js
test/integration/test-submit-custom.js
test/integration/test-submit-https.js
test/integration/test-submit-multi-nocallback.js
test/integration/test-submit-multi.js
test/integration/test-submit.js
test/run.js
test/static.js

Added `.eslint` and `editorconfig`, cleaned up.
/cc @DylanPiercey

Housecleaning, preparing for the release

---

lib/form_data.js
package.json
test/run.js

- Replaced win-spawn with cross-spawn

More housecleaning

---

.eslintrc
lib/form_data.js
package.json

Bumped version. Updated dependencies.
/cc @DylanPiercey

v1.0.0-rc4

---

.eslintrc
.istanbul.yml
.travis.yml
Readme.md
appveyor.yml
lib/form_data.js
package.json

- Dropped support for node@0.10
- Cleaned up code and tools.

Replaced async with asynckit

---

lib/form_data.js

Added `hasKnownLength` public method

---

test/common.js
test/integration/test-http-response.js
test/integration/test-submit-custom.js
test/integration/test-submit.js

Boilerplate code rediction

---

.gitignore
.travis.yml
appveyor.yml
package.json

to combat https://github.com/request/request/issues/1561

Pulling in fixed combined-stream

---

Readme.md

when using http library like axios in nodejs, I came across some problems when I tried to upload a file from a node server, some note about integration with axios should be added to help others.

docs(readme): add axios integration document

---

.eslintignore
.eslintrc
.gitignore
index.d.ts
package.json

Migrate TS typings from DefinitelyTyped/DefinitelyTyped here for the convenience of maintaining and usage.
This should fix #427

feat(typings): migrate TS typings #427

---

Readme.md

-Fixed: Eerror in the documentations as indicated in #439

---

package.json

Update combined-stream (fixes #422)

---

Readme.md
index.d.ts
lib/form_data.js
test/integration/test-set-boundary.js

This allows for deterministic payloads.
Closes #464

Add setBoundary method to FormData.

---

lib/form_data.js

Fixes: https://github.com/form-data/form-data/issues/563

fix: move util.isArray to Array.isArray

---

lib/form_data.js
package.json

[Fix] set `Symbol.toStringTag` when available
